#!/usr/bin/env node
// uploads: operator photo registry + short/long-term memory bridge for instruction imaging.
// Directive 2026-09-12 (session 01a097ba): every operator upload is saved into uploads/,
// hash-verified, cross-referenced at EVERY instruction-imaging step, and wired into memory
// (short-term = uploads/RECENT.md window, long-term = index.json + agent-memory receipts).
// Universal contract: docs/imaging-contract.md. Zero dependencies, deterministic stdout.
// CHAT-ONLY RULE: a photo viewable in chat but not persistable on disk gets a chat-only
// agent-memory perception receipt (confidence capped); bytes are re-requested when needed.

import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const DIR = 'uploads', INDEX = `${DIR}/index.json`, RECENT = `${DIR}/RECENT.md`, WINDOW = 8;
type Claim = { claim: string; evidence: string; confidence: string };
type Upload = { id: string; date: string; source: string; label: string; file: string; origin: string; bytes: number; sha256: string; w: number; h: number; claims: Claim[] };
type Ix = { schema: string; created: string; updated: string; lastId: number; uploads: Upload[] };

function argVal(args: string[], key: string): string | undefined {
  const pre = `--${key}=`;
  return args.filter((a) => a.startsWith(pre)).map((a) => a.slice(pre.length))[0];
}
const sha256buf = (b: Buffer): string => createHash('sha256').update(b).digest('hex');
const today = (): string => new Date().toISOString().slice(0, 10);

function load(): Ix {
  if (!existsSync(INDEX)) return { schema: 'uploads.v1', created: today(), updated: today(), lastId: 0, uploads: [] };
  const raw = JSON.parse(readFileSync(INDEX, 'utf8')) as Ix;
  if (raw.schema !== 'uploads.v1') { console.error(`bad schema ${raw.schema}`); process.exit(1); }
  raw.uploads.sort((a, b) => a.id.localeCompare(b.id));
  return raw;
}
function save(ix: Ix): void {
  ix.updated = today();
  ix.uploads.sort((a, b) => a.id.localeCompare(b.id));
  mkdirSync(DIR, { recursive: true });
  writeFileSync(INDEX, JSON.stringify(ix, null, 2) + '\n');
  writeFileSync(RECENT, block(ix, WINDOW));
}

// image dimensions: PNG IHDR + JPEG SOF scan (no decode, no deps)
function dims(buf: Buffer): { w: number; h: number } {
  if (buf.length > 24 && buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])))
    return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
  if (buf.length > 4 && buf[0] === 0xff && buf[1] === 0xd8) {
    let off = 2;
    while (off + 9 < buf.length) {
      if (buf[off] !== 0xff) { off++; continue; }
      const m = buf[off + 1];
      if (m >= 0xc0 && m <= 0xcf && m !== 0xc4 && m !== 0xc8 && m !== 0xcc) return { h: buf.readUInt16BE(off + 5), w: buf.readUInt16BE(off + 7) };
      off += 2 + buf.readUInt16BE(off + 2);
    }
  }
  return { w: 0, h: 0 };
}

// short-term memory: RECENT.md window (last n uploads, full context)
function block(ix: Ix, n: number): string {
  const lines = [
    '# UPLOADS SHORT-TERM MEMORY (auto-generated by tools/uploads.ts - do not edit by hand)',
    `window=${n} totalEntries=${ix.uploads.length} updated=${ix.updated}`,
    'Image agents: read this BEFORE perceiving. Full registry: uploads/index.json (long-term). Verify hashes before any render: node tools/uploads.ts verify',
    '',
  ];
  for (const u of ix.uploads.slice(-n)) {
    lines.push(`## ${u.id} ${u.date} ${u.w}x${u.h} ${u.file}`, `sha256=${u.sha256.slice(0, 12)} label="${u.label}" source=${u.source}`);
    for (const c of u.claims) lines.push(`- ${c.claim} (evidence: ${c.evidence}; confidence: ${c.confidence})`);
    lines.push('');
  }
  return lines.join('\n');
}

// long-term memory bridge: agent-memory perception receipt per ingest
function memoryReceipt(u: Upload, noMemory: boolean): string {
  if (noMemory || process.env.UPLOADS_NO_MEMORY === '1') return 'skipped';
  const r = spawnSync(process.execPath, ['tools/agent-memory.ts', 'add', 'perception', `--target=${u.file}`, '--tool=uploads ingest', `--claims=${JSON.stringify(u.claims)}`], { encoding: 'utf8' });
  const line = (r.stdout ?? '').trim().split('\n').filter(Boolean).pop() ?? 'spawn-failed';
  return line.startsWith('ADDED') ? line.replace('ADDED ', '') : line;
}

function cmdInit(): number {
  const existed = existsSync(INDEX);
  save(load());
  console.log(`UPLOADS_INIT dir=${DIR} entries=${load().uploads.length} ${existed ? 'existing' : 'created'}`);
  return 0;
}

function cmdIngest(args: string[]): number {
  const file = argVal(args, 'file');
  if (!file || !existsSync(file)) { console.error('usage: ingest --file=PATH [--label=L] [--source=chat|sandbox|web|photo] [--claims=\'[{"claim":..,"evidence":..,"confidence":..}]\'] [--no-memory]'); return 1; }
  const ix = load();
  const buf = readFileSync(file);
  const hash = sha256buf(buf);
  const dup = ix.uploads.find((u) => u.sha256 === hash);
  if (dup) { console.log(`UPLOADS_DUPLICATE id=${dup.id} sha256=${hash} file=${dup.file}`); return 0; }
  const claims: Claim[] = argVal(args, 'claims') ? JSON.parse(argVal(args, 'claims')!) : [];
  const label = argVal(args, 'label') ?? file.split('/').pop() ?? file;
  const source = argVal(args, 'source') ?? 'sandbox';
  const inRepo = file === DIR || file.startsWith(`${DIR}/`);
  const dest = inRepo ? file : join(DIR, today(), file.split('/').pop() ?? 'upload.bin');
  if (!inRepo) { mkdirSync(dest.slice(0, dest.lastIndexOf('/')), { recursive: true }); copyFileSync(file, dest); }
  ix.lastId += 1;
  const u: Upload = { id: `U-${String(ix.lastId).padStart(4, '0')}`, date: today(), source, label, file: dest, origin: file, bytes: buf.length, sha256: hash, ...dims(buf), claims };
  if (!claims.length) claims.push({ claim: `ingested upload ${u.id} (${label})`, evidence: `sha256 ${hash.slice(0, 16)} bytes=${buf.length}`, confidence: 'HIGH' });
  ix.uploads.push(u);
  save(ix);
  console.log(`INGESTED id=${u.id} file=${dest} sha256=${hash} ${u.w}x${u.h} bytes=${buf.length}`);
  console.log(`MEMORY ${memoryReceipt(u, args.includes('--no-memory'))}`);
  console.log(`SHORT_TERM ${RECENT} window=${WINDOW}`);
  return 0;
}

function cmdList(args: string[]): number {
  const ix = load();
  const n = Number(argVal(args, 'n') ?? '0');
  const rows = n > 0 ? ix.uploads.slice(-n) : ix.uploads;
  for (const u of rows) console.log(`${u.id}\t${u.date}\t${u.w}x${u.h}\t${u.bytes}B\t${u.label}\t${u.file}`);
  console.log(`UPLOADS count=${rows.length}/${ix.uploads.length}`);
  return 0;
}

function cmdRecent(args: string[]): number {
  console.log(block(load(), Number(argVal(args, 'n') ?? String(WINDOW))).replace(/\n$/, ''));
  return 0;
}

function cmdRefs(args: string[]): number {
  const ix = load();
  const ids = (argVal(args, 'ids') ?? '').split(',').map((s) => s.trim()).filter(Boolean);
  const recentN = Number(argVal(args, 'recent') ?? '0');
  let rows = ix.uploads;
  if (ids.length) rows = rows.filter((u) => ids.includes(u.id));
  else if (recentN > 0) rows = rows.slice(-recentN);
  else if (!args.includes('--all')) rows = rows.slice(-WINDOW);
  console.log('=== UPLOADS CROSSREF BLOCK START (byte-identical every step; verify before render) ===');
  for (const u of rows) console.log(`UPLOAD ${u.id} file=${u.file} sha256=${u.sha256} ${u.w}x${u.h} label="${u.label}" claims=${u.claims.length}`);
  console.log('RULE: node tools/uploads.ts verify before each render; a hash mismatch refuses the render. Missing visual evidence: node tools/uploads.ts gate issues the photo request.');
  console.log('=== UPLOADS CROSSREF BLOCK END ===');
  return 0;
}

function cmdVerify(): number {
  const ix = load();
  let ok = 0, bad = 0;
  for (const u of ix.uploads) {
    if (!existsSync(u.file)) { console.log(`${u.id}\tMISSING\t${u.file}`); bad++; continue; }
    const h = sha256buf(readFileSync(u.file));
    if (h === u.sha256) { console.log(`${u.id}\tOK\t${u.file}`); ok++; } else { console.log(`${u.id}\tMISMATCH\t${u.file}\t${h}`); bad++; }
  }
  console.log(`UPLOADS_VERIFY ok=${ok} bad=${bad}`);
  return bad === 0 ? 0 : 1;
}

const tokens = (s: string): string[] => s.toLowerCase().split(/[^a-z0-9]+/).filter((t) => t.length >= 4);
function cmdGate(args: string[]): number {
  const raw = argVal(args, 'claims');
  if (!raw) { console.error('usage: gate --claims=\'[{"claim":"..."}]\' [--match=U-0001,U-0002]'); return 1; }
  const ix = load();
  const claims: Claim[] = JSON.parse(raw).map((c: any) => ({ claim: c.claim ?? String(c), evidence: c.evidence ?? 'pending', confidence: c.confidence ?? 'PENDING' }));
  const matchIds = (argVal(args, 'match') ?? '').split(',').map((s) => s.trim()).filter(Boolean);
  let covered = 0;
  const missing: string[] = [];
  claims.forEach((c, i) => {
    const id = matchIds[i];
    const auto = ix.uploads.filter((u) => tokens(c.claim).some((t) => tokens(`${u.label} ${u.claims.map((x) => x.claim).join(' ')}`).includes(t))).map((u) => u.id);
    if (id || auto.length) { covered++; console.log(`COVERED\t${c.claim}\trefs=${id ?? auto.join(',')}`); }
    else { missing.push(c.claim); console.log(`MISSING\t${c.claim}`); }
  });
  console.log(`GATE covered=${covered} missing=${missing.length}`);
  if (missing.length) {
    console.log('PHOTOS REQUESTED (every missing claim, every time - render is refused until covered):');
    missing.forEach((m, i) => console.log(`${i + 1}. PHOTO NEEDED: ${m} - attach in chat (agent saves to uploads/) or name a file path.`));
    return 2;
  }
  return 0;
}

// selftest: isolated tmpdir, synthetic PNG/JPEG, every subcommand
function tinyPng(w: number, h: number): Buffer {
  const head = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 13, 0x49, 0x48, 0x44, 0x52]);
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(w, 0); ihdr.writeUInt32BE(h, 4); ihdr[8] = 8; ihdr[9] = 2;
  return Buffer.concat([head, ihdr, Buffer.alloc(4), Buffer.from([0, 0, 0, 0, 0x49, 0x45, 0x4e, 0x44])]);
}
function cmdSelftest(): number {
  process.env.UPLOADS_NO_MEMORY = '1';
  const tmp = mkdtempSync(join(tmpdir(), 'uploads-selftest-'));
  const checks: string[] = [];
  const ok = (name: string, cond: boolean) => checks.push(`${cond ? 'ok' : 'FAIL'} ${name}`);
  function run(rest: string[]): { out: string; rc: number } {
    const origLog = console.log, origErr = console.error; let buf = '';
    console.log = (...a: any[]) => { buf += a.join(' ') + '\n'; };
    console.error = (...a: any[]) => { buf += a.join(' ') + '\n'; };
    let rc = 1;
    try { rc = dispatch(rest); } finally { console.log = origLog; console.error = origErr; }
    return { out: buf, rc };
  }
  writeFileSync(join(tmp, 'a.png'), tinyPng(64, 48));
  writeFileSync(join(tmp, 'b.jpg'), Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0, 16, 0x4a, 0x46, 0x49, 0x46, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0xff, 0xc0, 0, 17, 8, 0, 32, 0, 40, 3, 0, 0x11, 0, 2, 0x11, 0, 1, 0x11, 0]));
  const cwd = process.cwd(); process.chdir(tmp);
  try {
    run(['init']);
    ok('init creates index + RECENT', existsSync(join(tmp, INDEX)) && existsSync(join(tmp, RECENT)));
    const r1 = run(['ingest', `--file=${join(tmp, 'a.png')}`, '--label=riser board photo', '--source=chat']);
    ok('ingest prints INGESTED U-0001 64x48', /INGESTED id=U-0001 .*64x48/.test(r1.out) && r1.rc === 0);
    ok('ingest copied into dated dir', existsSync(join(tmp, `uploads/${today()}/a.png`)));
    ok('jpeg dims parsed 40x32', /40x32/.test(run(['ingest', `--file=${join(tmp, 'b.jpg')}`, '--label=jpeg dims probe']).out));
    ok('duplicate detected', /UPLOADS_DUPLICATE id=U-0001/.test(run(['ingest', `--file=${join(tmp, 'a.png')}`]).out));
    ok('list counts 2/2', /UPLOADS count=2\/2/.test(run(['list']).out));
    const rr = run(['recent', '--n=1']);
    ok('recent shows window + sha12', /SHORT-TERM MEMORY/.test(rr.out) && /sha256=[0-9a-f]{12}/.test(rr.out));
    const rf = run(['refs', '--ids=U-0001']);
    ok('refs block markers stable', rf.out.includes('UPLOAD U-0001 file=') && rf.out.includes('CROSSREF BLOCK END'));
    const rv = run(['verify']);
    ok('verify ok=2 bad=0', /UPLOADS_VERIFY ok=2 bad=0/.test(rv.out) && rv.rc === 0);
    const rg1 = run(['gate', '--claims=' + JSON.stringify([{ claim: 'riser board orientation' }])]);
    ok('gate auto-covers by token overlap', /COVERED/.test(rg1.out) && /missing=0/.test(rg1.out) && rg1.rc === 0);
    const rg2 = run(['gate', '--claims=' + JSON.stringify([{ claim: 'panel sticker legend' }])]);
    ok('gate missing prints numbered photo request', /PHOTOS REQUESTED/.test(rg2.out) && /1\. PHOTO NEEDED: panel sticker legend/.test(rg2.out) && rg2.rc === 2);
    ok('claims render in RECENT block', /ingested upload U-0001/.test(run(['recent']).out));
    ok('unknown command rc=1 usage', run(['bogus']).rc === 1 && run(['bogus']).out.includes('usage: uploads'));
  } finally { process.chdir(cwd); rmSync(tmp, { recursive: true, force: true }); }
  const failed = checks.filter((c) => c.startsWith('FAIL'));
  for (const c of checks) console.log(c);
  console.log(`UPLOADS_SELFTEST=${failed.length ? 'FAIL' : 'PASS'} checks=${checks.length}`);
  return failed.length ? 1 : 0;
}

function dispatch(argv: string[]): number {
  const [cmd, ...rest] = argv;
  if (cmd === 'init') return cmdInit();
  if (cmd === 'ingest') return cmdIngest(rest);
  if (cmd === 'list') return cmdList(rest);
  if (cmd === 'recent') return cmdRecent(rest);
  if (cmd === 'refs') return cmdRefs(rest);
  if (cmd === 'verify') return cmdVerify();
  if (cmd === 'gate') return cmdGate(rest);
  if (cmd === 'selftest') return cmdSelftest();
  console.error('usage: uploads <init|ingest|list|recent|refs|verify|gate|selftest>');
  return 1;
}
process.exit(dispatch(process.argv.slice(2)));
